// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240922191141_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 52,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ProductName = "Small Steel Ball"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 14,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ProductName = "Awesome Metal Table"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 76,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ProductName = "Awesome Cotton Bike"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 53,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ProductName = "Intelligent Metal Table"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 78,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ProductName = "Licensed Frozen Towels"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 86,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ProductName = "Sleek Steel Fish"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 65,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ProductName = "Incredible Steel Pants"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 28,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ProductName = "Incredible Fresh Shirt"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 74,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ProductName = "Licensed Steel Chicken"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 79,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ProductName = "Unbranded Frozen Towels"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 63,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ProductName = "Intelligent Wooden Table"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 98,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ProductName = "Sleek Metal Towels"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 87,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ProductName = "Unbranded Metal Tuna"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 87,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ProductName = "Handcrafted Metal Cheese"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 12,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ProductName = "Sleek Concrete Chips"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 88,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ProductName = "Licensed Soft Car"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 57,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ProductName = "Tasty Steel Hat"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 35,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ProductName = "Sleek Frozen Mouse"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 90,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ProductName = "Sleek Soft Car"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 72,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ProductName = "Handcrafted Steel Shirt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
